USE [master]
GO

/****** Object:  Database [BatchesInfo]    Script Date: 18.11.2015 09:55:36 ******/
CREATE DATABASE [BatchesInfo]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BatchesInfo', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\BatchesInfo.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'BatchesInfo_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\BatchesInfo_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [BatchesInfo] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BatchesInfo].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [BatchesInfo] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [BatchesInfo] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [BatchesInfo] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [BatchesInfo] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [BatchesInfo] SET ARITHABORT OFF 
GO

ALTER DATABASE [BatchesInfo] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [BatchesInfo] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [BatchesInfo] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [BatchesInfo] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BatchesInfo] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [BatchesInfo] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [BatchesInfo] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BatchesInfo] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [BatchesInfo] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BatchesInfo] SET  DISABLE_BROKER 
GO

ALTER DATABASE [BatchesInfo] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BatchesInfo] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BatchesInfo] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BatchesInfo] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [BatchesInfo] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BatchesInfo] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [BatchesInfo] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BatchesInfo] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [BatchesInfo] SET  MULTI_USER 
GO

ALTER DATABASE [BatchesInfo] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [BatchesInfo] SET DB_CHAINING OFF 
GO

ALTER DATABASE [BatchesInfo] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [BatchesInfo] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [BatchesInfo] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [BatchesInfo] SET  READ_WRITE 
GO




USE [BatchesInfo]
GO

/****** Object:  Table [dbo].[BatchProperties]    Script Date: 18.11.2015 09:58:10 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[BatchProperties](
	[batchname] [nchar](250) NOT NULL,
	[key] [nchar](100) NOT NULL,
	[value] [nchar](250) NULL,
 CONSTRAINT [PK_BatchProperties] PRIMARY KEY CLUSTERED 
(
	[batchname] ASC,
	[key] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


USE [BatchesInfo]
GO

/****** Object:  Table [dbo].[BatchStatus]    Script Date: 18.11.2015 09:58:44 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[BatchStatus](
	[batchname] [nchar](100) NOT NULL,
	[batchid] [nchar](50) NOT NULL,
	[start_time] [datetime] NULL,
	[start_init_time] [datetime] NULL,
	[start_load_time] [datetime] NULL,
	[start_transform_time] [datetime] NULL,
	[start_save_time] [datetime] NULL,
	[start_cleanup_time] [datetime] NULL,
	[finish_time] [datetime] NULL,
	[comment] [text] NULL,
	[status] [nchar](20) NULL,
 CONSTRAINT [PK_BatchStatus] PRIMARY KEY CLUSTERED 
(
	[batchname] ASC,
	[batchid] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO